consumer_key = "1JNJlIgHGgQF213iVzmgB7LSl"

consumer_secret = "pH3cEv9nQFv4r9rS3OhV6PcuaQhO8cZyv5WpyNfFd2Rlxrpr6p"

access_token = "1469761271709028359-Ac9jwcGkZmaXFC7yLgzlHGkM6ProjC"

access_token_secret = "hXW5SqHGVpOogxnnKDrXJdDdC5Nk1lnMFiyiu6hRJUx88"

bearer_token = "AAAAAAAAAAAAAAAAAAAAAGPIWwEAAAAA6L7Pk7nWV0i7G%2FS7W2pIdnEOEUc%3DqicKzjYrHwqHHHsT35CHcY0wvTCWuNkPyOZ3PEQy8iacruf9a9"